### ISSUE TITLE
Slow/no new releases since four days (causing out of sync version upgrades)

### ISSUE THREAD

**Issue by lovetheguitar** [renovatebot/pre-commit-hooks#1945]
I have a package rule to update the used renovatebot docker image and pre-commit validation hook simultaneously.

Is it possible to either speed up this release here or change the rule somehow that only matching versions (ignoring the docker sha) are chosen?

```json
"packageRules": [
    {
      "groupName": "renovate bot docker image and pre-commit validation hook",
      "groupSlug": "renovate-docker-image-and-pre-commit-hook",
      "matchPackageNames": ["renovate/renovate", "renovatebot/pre-commit-hooks"]
    }
  ]
```

Thanks a lot for your great work. :)

**Comment by viceice** [comment]
there's not much we can do. it's now releasing regularly again by renovate.
