### ISSUE TITLE
Hook fails to install with node LTS v22

### ISSUE THREAD

**Issue by wwuck** [renovatebot/pre-commit-hooks#2527]
I have node installed with `fnm`.  When I was using node v20 I had no problems installing this hook with pre-commit.  After I switched to v22 with fnm the hook install just hangs and doesn't complete. Reverting node to v20 with fnm allows the hook to install again.

Removing all node versions from fnm also doesn't work because then pre-commit goes to install node v23 itself which is also causing hook install to hang.

I can't see any way to get verbose/debug info from pre-commit on hook install and it looks like there won't be any feature added to support that. (https://github.com/pre-commit/pre-commit/issues/3254)

**Comment by jonesbusy** [comment]
Same here. For some reason it work with `22.10.0` but hang with `22.11.0`

Not sure exactly where to look

Not sure if nodeenv issue or precommit issue. Could be similar to https://github.com/renovatebot/pre-commit-hooks/issues/2460

**Comment by viceice** [comment]
Seems like a tooling error, like the other mentioned issue. There's nothing we can do here.
